# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PersonApp', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usr1', to='PersonApp.Person')),
                ('departure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dep_loc', to='Location.Location')),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dest_loc', to='Location.Location')),
                ('passenger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr2', to='PersonApp.Person')),
            ],
        ),
    ]
