# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usr1', to=settings.AUTH_USER_MODEL)),
                ('departure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dep_loc', to='Location.Location')),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dest_loc', to='Location.Location')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usr2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
