# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PersonApp', '0001_initial'),
        ('Location', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides1', to='Location.Location')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides2', to='Location.Location')),
                ('passengers', models.ManyToManyField(blank=True, null=True, to='PersonApp.Person')),
            ],
        ),
    ]
