# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonApp', '0001_initial'),
        ('Rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='passenger',
        ),
        migrations.AddField(
            model_name='ride',
            name='passengers',
            field=models.ManyToManyField(blank=True, null=True, to='PersonApp.Person'),
        ),
    ]
