# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0002_auto_20160313_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usr1', to='PersonApp.Person'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='passenger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr2', to='PersonApp.Person'),
        ),
    ]
