# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0003_auto_20160313_1019'),
        ('Rides', '0003_auto_20160313_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides1', to='Location.Location'),
        ),
        migrations.AddField(
            model_name='ride',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides2', to='Location.Location'),
        ),
    ]
