# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='profile_photo',
            new_name='profile_pic',
        ),
    ]
