# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='State_Prov',
            new_name='StateProv',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='zip_code',
            new_name='zipCode',
        ),
    ]
