# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0003_auto_20160313_1011'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_loc', to='Rides.Ride'),
        ),
        migrations.AddField(
            model_name='location',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_loc', to='Rides.Ride'),
        ),
    ]
