# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_auto_20160313_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='location',
            name='destination',
        ),
    ]
